eureka:
  client:
    register-with-eureka: false

server:
  port: 8080
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: students
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/students/**
          - id: schools
            uri: http://localhost:8070
            predicates:
              - Path=/api/v1/schools/**

